# yaml-language-server: $schema=https://operagents.yyydl.top/schemas/config.schema.json

agents:
  Mike:
    backend:
      type: user
    system_template: ""
    user_template: |-
      {% for event in timeline.past_events(agent) -%}
      {% if event.type_ == "act" -%}
      {{ event.character.agent_name }}({{ event.character.name }}): {{ event.content }}
      {%- endif %}
      {%- endfor %}
    scene_summary_system_template: ""
    scene_summary_user_template: |-
      {% for event in agent.memory.get_memory_for_scene(scene) -%}
      {% if event.type_ == "observe" -%}
      {{ event.content }}
      {%- elif event.type_ == "act" -%}
      {{ agent.name }}({{ event.character.name }}): {{ event.content }}
      {%- endif %}
      {%- endfor %}
      {% for event in timeline.past_events_in_scene(agent, scene) -%}
      {% if event.type_ == "act" -%}
      {{ event.character.agent_name }}({{ event.character.name }}): {{ event.content }}
      {%- endif %}
      {%- endfor %}
  John:
    backend:
      type: openai
      model: gpt-3.5-turbo-16k-0613
      temperature: 0.3
    system_template: |-
      Your name is {{ agent.name }}.
      Current scene is {{ timeline.current_scene.name }}.
      {% if timeline.current_scene.description -%}
      {{ timeline.current_scene.description }}
      {%- endif -%}
      You are acting as {{ timeline.current_character.name }}.
      {% if timeline.current_character.description -%}
      {{ timeline.current_character.description }}
      {%- endif -%}
      Please continue the conversation on behalf of {{ agent.name }}({{ timeline.current_character.name }}) based on your known information and make your answer appear as natural and coherent as possible.
      Please answer directly what you want to say and keep your reply as concise as possible.
    user_template: |-
      Here is your chat history:
      {% for event in timeline.past_events(agent) -%}
      {% if event.type_ == "act" -%}
      {{ event.character.agent_name }}({{ event.character.name }}): {{ event.content }}
      {%- endif %}
      {%- endfor %}
    scene_summary_system_template: |-
      Your name is {{ agent.name }}.
      Your task is to summarize the historical dialogue records according to the current scene, and summarize the most important information.
    scene_summary_user_template: |-
      {% for event in agent.memory.get_memory_for_scene(scene) -%}
      {% if event.type_ == "observe" -%}
      {{ event.content }}
      {%- elif event.type_ == "act" -%}
      {{ agent.name }}({{ event.character.name }}): {{ event.content }}
      {%- endif %}
      {%- endfor %}
      {% for event in timeline.past_events_in_scene(agent, scene) -%}
      {% if event.type_ == "act" -%}
      {{ event.character.agent_name }}({{ event.character.name }}): {{ event.content }}
      {%- endif %}
      {%- endfor %}

opening_scene: talking

scenes:
  talking:
    description:
    flow:
      type: order
    director:
      type: model
      backend:
        type: openai
        model: gpt-3.5-turbo-16k-0613
        temperature: 0.3
      system_template: |-
        You are the director of the scene. Please observe the ongoing discussion and decide whether more communication is needed between user and AI assistant. If you think the conversation is over, please type "finish" to end the scene.
      user_template: |-
        Here is the chat history:
        {% for event in timeline.scene_events(timeline.current_scene) -%}
        {% if event.type_ == "act" -%}
        {{ event.character.agent_name }}({{ event.character.name }}): {{ event.content }}
        {%- endif %}
        {%- endfor %}
      allowed_scenes: []
      finish_flag: finish
    characters:
      user:
        agent_name: Mike
      ai assistant:
        description: |-
          You are a helpful assistant.
        agent_name: John
