name: Generate Config Schema
description: Generate the JSON schema for operagents config

inputs:
  output-path:
    description: Output path for the generated schema
    required: false
    default: "operagents/config/operagents.schema.json"

runs:
  using: "composite"
  steps:
    - name: Generate
      run: |
        poetry run python ./scripts/generate_config_schema.py ${{ inputs.output-path }}
        echo "output-path=${{ inputs.output-path }}" >> "$GITHUB_OUTPUT"
      shell: bash
