name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  generate-config-schema:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Generate
        id: generate-schema
        uses: ./.github/actions/generate-schema
        with:
          output-path: operagents/config/config.schema.json

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: operagents-config-schema
          path: operagents/config/config.schema.json
          retention-days: 1
          if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    needs: generate-config-schema
    steps:
      - uses: actions/checkout@v5
        with:
          ref: gh-pages
          fetch-depth: 1

      - name: Download Schema
        uses: actions/download-artifact@v5
        with:
          name: operagents-config-schema
          path: schemas/

      - run: |
          ls -al ./schemas/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4
