name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  generate-config-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Generate
        id: generate-schema
        uses: ./.github/actions/generate-schema

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: operagents-config-schema
          path: ${{ steps.generate-schema.outputs.output-path }}
          retention-days: 1

  build:
    runs-on: ubuntu-latest
    needs: generate-config-schema
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 1

      - name: Download Schema
        uses: actions/download-artifact@v2
        with:
          name: operagents-config-schema
          path: schemas/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: website
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4
